name: Deploy Email Service

on:
  push:
    paths:
      - 'services/email/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.0'

    - name: Install dependencies
      run: |
        cd services/email
        yarn install

    - name: Build project
      run: |
        cd services/email
        yarn build

    - name: Run Prisma Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_EMAIL }}
      run: |
        cd services/email
        yarn migrate:prod

    - name: Deploy to Vercel
      run: |
        cd services/email
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }} --yes
