name: Deploy Api-gateway Service

on:
  push:
    branches:
      - main  #
    paths:
      - 'api-gateway/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.0'

    - name: Install dependencies
      run: |
        cd api-gateway
        yarn install

    - name: Build project
      run: |
        cd api-gateway
        yarn build

    - name: Deploy to Vercel
      env:
        AUTH_ENDPOINT: ${{ secrets.AUTH_ENDPOINT }}
        API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
        ROOM_ENDPOINT: ${{ secrets.ROOM_ENDPOINT }}
        BOOKING_ENDPOINT: ${{ secrets.BOOKING_ENDPOINT }}
        USER_ENDPOINT: ${{ secrets.USER_ENDPOINT }}
      run: |
        cd api-gateway
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }} --yes
