name: Deploy Api-gateway Service

on:
  push:
    paths:
      - 'api-gateway/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.0'

    - name: Install dependencies
      run: |
        cd api-gateway
        yarn install

    - name: Build project
      run: |
        cd api-gateway
        yarn build

    - name: Deploy to Vercel
      run: |
        cd api-gateway
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }} --yes
